version: '3.3'
services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notesapp_reactjs_frontend
    env_file: .env.development
    volumes:
      - 'notesapp_reactjs_frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
